### ISSUE TITLE
Choice Remembering

### ISSUE THREAD

**Issue by Infinite7Soul** [Elringus/NaninovelWeb#102]
Maybe I didn't notice it but I can't find a way to make long-term consequences in my game via NaniNovel. RenPy has flags that I can use in the future (https://www.renpy.org/wiki/renpy/doc/tutorials/Remembering_User_Choices) but what about NaniNovel?

**Comment by Elringus** [comment]
Use custom variables: https://naninovel.com/guide/custom-variables.html

Please follow the guide to open a bug report (https://naninovel.com/support/) when submitting tickets here; you can always contact the support via the discord if you have any questions.
