### ISSUE TITLE
Error unity 2018.2.11f 

### ISSUE THREAD

**Issue by slove3000** [Elringus/NaninovelWeb#103]
**Describe the bug**

**Unity version**
Specify Unity version you are using, e.g.: 2018.2.11f.

**OS (when editor-related)**
Which operating system you're running the editor under, e.g.: Windows 10

**Platform**
Which target platform you're using, e.g.: PC

I want to get a adapter version of the Naninovel, I am using the unity 2018.2.11f, my unity ID slove3000@163.com.  

Thanks

**Comment by Elringus** [comment]
Hi, The minimum supported Unity version at the moment is 2019.2.

We can share older versions of the package, which target previous Unity versions, but we won't be able to provide support for them; minimum supported Unity versions for the oldest available package is 2018.3, though.

Feel free to contact the support via our Discord server for more info: https://naninovel.com/support/
