### ISSUE TITLE
Add an option to disable hidePreviewTimer in Game Settings Message Speed Slider

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#112]
Like some visual novels, the preview printer in the game settings is always visible. 

![screenshot 2020-01-22 115916](https://user-images.githubusercontent.com/5277788/72864723-fa380300-3d0f-11ea-8a9c-ca3410b3f8d1.jpg)
> Screenshot from NEKOPARA vol.1

But currently, Naninovel only enables the preview printer when changing the message speed.
This will prevent the user to preview font change or transparency.

Consider adding a setting to make the preview printer always visible in the text setting section.

**Comment by edisonlee55** [comment]
Closing this issue.
I have just figured out that using an Event Trigger can implement this feature.
Sorry, I am still trying hard to learn Unity (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄).

**Comment by edisonlee55** [comment]
Sorry for reopening this issue again.

But the `hidePreviewTimer` in `Game Settings Message Speed Slider` script will hide my preview printer after the preview time.

Set preview time to a huge number can address this issue, but not a good solution.

Add an option to disable `hidePreviewTimer` in `Game Settings Message Speed Slider` script would fix this.

**Comment by Elringus** [comment]
Just remove (or disable) `Canvas Group` component on the root of the preview printer and it won't ever be hidden. 

Please use our discord's #support channel for further requests please: https://naninovel.com/support/#developer-support
