### ISSUE TITLE
There is a sorting issue when using LwrpUIDefault.

### ISSUE THREAD

**Issue by ho-dragon** [Elringus/NaninovelWeb#115]
Options set for my project:
 - Canvas RenderMode : Sceen Space - Camera
 - RenderPipeline : UniversalRenderPipeline
 - Unity version : 2019.3.0f6
 - OS : Windows 10
 - Platform : Android
 - BlendModes Version : 3.9

I bought a BlendModes from the Asset Store and am using it.
I think it's a very good UI plugin.
My project uses the URP rendering pipeline.
I checked the Documentation and set RenderFeatures. I have verified that it works.

But I am being faced sorting problem.
UI using BlendMode and UI not using appear to be sorting groups separated.

Sorting is not possible as in the example below.
ex) A(BlendMode UI) - B - C(BlendMode UI)

When I checked through FrameDebuger, it seemed that the two types of UI had separate renderPassEvent.

Additionally,
I used Unity's default RenderPipeline, so there was no problem.
So it seems to be a problem that only happens in URP.

I amin a situation where we need to use Canvas ScreenSapce as Camera.
I hope this problem will be solved.
I will wait for your reply.
Thank you.

**Comment by ho-dragon** [comment]
Another problem exists. When using URP, the BlendMode UI is not visible in the 'Scene' Window in editor. Only visible in the 'Game' Window.

**Comment by Elringus** [comment]
This repo is for Naninovel visual novel engine (hence the name). Please use contact method specified in the documentation for the plugin you're using to contact the support.
