### ISSUE TITLE
Allow using state variables in action parameters

### ISSUE THREAD

**Issue by wrighp** [Elringus/NaninovelWeb#14]
If this is already possible it may not be clear in the documentation how this is done.

I’m looking to set a state variable externally from code (the player’s custom name) and print out dialogue that includes it.
The documentation shows how the $ works for defines however the documentation doesn’t explain if it is possible with set/state variables or how to go about printing referenced variables like this.

**Comment by wrighp** [comment]
Thank you for responding so quickly and thanks for the solution!
One way to make the action work well without possibly interfering with normal text would be to add a parameter to @print that only does the string interpolation when set to true.

**Comment by Elringus** [comment]
Yeah, that will do, but I was looking to not just allow printing the state variables, but use them anywhere in the action parameters, eg:

```
@set a=10
@char Haruhi pos:[a]
```

And this will require resolving the actual parameter values before the action execution (aka late binding); but at the same time will complicate actions undo mechanism and some other things. Maybe I would have to change some stuff before implementing this.

**Comment by wrighp** [comment]
Could you consider having variables use { } when they need to be bracketed? This would make the difference between actions and variables more clear. [c# uses curly brackets to denote variables in strings already, so it wouldn't be that out of place syntactically.](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)

**Comment by Elringus** [comment]
Ah, sure. I've not decided anything yet, those examples were just for example. Curly braces indeed looks more appropriate. Thanks for the suggestion!

**Comment by Elringus** [comment]
Implemented in `v1.3.0-beta`.
https://naninovel.com/api/#set
