### ISSUE TITLE
Progress tracking 

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#22]
Expose API to get total / read number of lines (unique novel actions executed at least once) to track the game progress (completeness).

**Comment by Samuel-Harbord** [comment]
You could also add endings reached with a higher weight (configurable).

**Comment by Elringus** [comment]
> 
> 
> You could also add endings reached with a higher weight (configurable).

Well, an "ending" is a kinda subjective thing, that could make sense for one game, but not for another. I don't think it's possible to introduce a generic concept of endings to the engine. However, you can just create a custom state variable, that will trigger when user reads through a particular part of the script, which you consider an "ending" and then use this variable to calculate the progress.

**Comment by Elringus** [comment]
Implemented in `v1.5.0-beta`.

Use `CalculateProgress()` expression function in novel scripts to get progress in 0.0 to 1.0 range, eg `@set progress=CalculateProgress()`. 

`NovelScriptPlayer` engine service now also exposes `TotalActionCount` and `PlayedActionCount` properties.
