### ISSUE TITLE
Update choice handlers to support image and position

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#33]
**Describe your idea**
Allow providing `image` and `pos` (optional) params to the choice handler. Make the choice description text param optional.

**Describe possible use cases**
Making an "interactive map" with the `@choice` actions.

**Share reference implementations**
https://www.youtube.com/watch?v=s5_yvgkmv0c

**Comment by Lexzaviel** [comment]
Well, maybe it @choice with a variable. More you play in the game you get more unlock?

**Comment by Elringus** [comment]
Uhm, do you mean adding some parameter to the `@choice` actions, which should unlock something based on reading progress? I don't really get it, sorry.

**Comment by Lexzaviel** [comment]
Well, that is it.

**Comment by Elringus** [comment]
In this case it's already possible with conditional and set expressions. Check out examples in the API reference: 

https://naninovel.com/api/#if
https://naninovel.com/api/#set
https://naninovel.com/api/#choice

**Comment by Elringus** [comment]
Implemented in `v1.4.0-beta`.

https://naninovel.com/guide/choices.html#buttonarea-choice-handler
https://www.youtube.com/watch?v=cNRNgk5HhKQ
