### ISSUE TITLE
Add an option to auto-play a novel script in the title menu

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#37]
>**Describe your idea**
A clear and concise description what should we change or add.

Add the support for the novel scripts to script the title UI.

>**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

Currently, the title UI is unable to be scripted by the novel scripts, we must click "New Game" button to start the first script. But in the title UI, there are have many different components that should be controlled using the novel scripts. (Like title BGM, background, effect, etc.)

>**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

Most VN engines and games can script their title UI by their own novel script or by the editor.

**Comment by Elringus** [comment]
Well, novel script is not a markup language, so I don't think it's a good idea to write UI layout with it. 

That said, if I've got you correctly, your main requirement is to be able to use novel scripts while in the title menu to control backgrounds, music, etc. While it's more appropriate to setup all this stuff via the title UI prefab and custom C# scripts, I can see that in some cases (eg, when user can't or don't want to write C# scripts) a feature to automatically play a novel script in the title menu could be useful. 

Will it work for you, if we add an option to the engine configuration menu, where you can specify a novel script, which will be automatically played after engine initialization (just before showing the title menu)?

**Comment by edisonlee55** [comment]
Yes, I think it'll work for me. Thanks! Σ(ノ°▽°)ノ

**Comment by Elringus** [comment]
Implemented in `v1.4.0-beta`.

![](https://i.gyazo.com/8570f13546e73f2ae23e4e43e575d8aa.png)
