### ISSUE TITLE
Managed text generate tool can't work properly in macOS

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#39]
>**Describe the bug**

Managed text generate tool can't work properly in macOS. I think the output path code is hardcoded to Windows path format. (eg, if I output to `./Resources/Text`, the outputted file will in `./Resources/` with the file name `Text\CharacterNames.txt`, `Text\UIBacklog.txt ...`)

>**To Reproduce**
>1. Go to '...'
>2. Click on '....'
>3. Scroll down to '....'
>4. See error

1. Use macOS to open the project
2. Open managed text generate tool in `Naninovel -> Tools -> Managed Text` context menu.
3. Choose any path you want to generate the managed text documents
4. Open Finder to the parent directory of the selected directory (The generated files are not visible in the Unity project tab.)
4. You will notice that the documents are generated in the parent directory of the selected directory (With the file name `<selected_directory_name>\CharacterNames.txt`, `<selected_directory_name>\UIBacklog.txt ...`)
5. See error

>**Expected behavior**

The managed text documents should be generated in the selected directory with file name `CharacterNames.txt`, `UIBacklog.txt ...`

>**Screenshots**

**Generate the managed text documents in `./Resources/TestText`**
<img width="508" alt="螢幕快照 2019-04-04 上午11 32 17" src="https://user-images.githubusercontent.com/5277788/55527958-c67ee480-56cd-11e9-99f4-e32f68a9bc1e.png">

**After generated, the generated files are not visible in the Unity project tab.**
<img width="1148" alt="螢幕快照 2019-04-04 上午11 33 23" src="https://user-images.githubusercontent.com/5277788/55528017-fc23cd80-56cd-11e9-965e-733c30e65475.png">

**But visible in Finder with file name `TestText\CharacterNames.txt`, `TestText\UIBacklog.txt ...`**
<img width="299" alt="螢幕快照 2019-04-04 上午11 33 51" src="https://user-images.githubusercontent.com/5277788/55528067-283f4e80-56ce-11e9-9427-944f823934f7.png">

>**Naninovel version**
Version of the engine as displayed in `Naninovel -> About` window, e.g.: 1.0.12-beta

v1.3.2-beta build 2019-03-08

>**Unity version**
Specify Unity version you are using, e.g.: 2018.3.5f2.

2018.3.11f1

>**OS (when editor-related)**
Which operating system you're running the editor under, e.g.: Windows 10

macOS 10.14.4

>**Platform**
Which target platform you're using, e.g.: WebGL

PC, Mac & Linux Standalone (Mac OS X)

**Comment by Elringus** [comment]
Thanks for the detailed report! I'll do my best to check and fix this before the next release.

**Comment by Elringus** [comment]
Fixed in `v1.4.0-beta`.
