### ISSUE TITLE
Branch Tree Menu

### ISSUE THREAD

**Issue by LinkuArt** [Elringus/NaninovelWeb#40]
> **Describe your idea**
> A clear and concise description what should we change or add.
> 

_Add a menu where you can see ongoing story branches & endings or those who you have finished._

> **Describe possible use cases**
> A concrete example or two on how the proposed change could be used.

_Access from the start menu to see which branches you have finished. And/or access from a menu or shortkey during the gameplay._

> 
> **Share reference implementations**
> If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

_Here is a (_**[image](https://i.imgur.com/YuBbbxu.jpg)**_) example. There are similar branch trees in other visual novel games._

**Comment by Elringus** [comment]
Thanks for the suggestion! Naninovel doesn't currently have a concept of story branches or endings; they're something developer of the game may or may not use in the project, hence I'm not sure it makes sense to introduce them as core concepts to the engine. Maybe it will be more appropriate to make a standalone system (example implementation), that could be added to the project when needed.

**Comment by LinkuArt** [comment]
> Thanks for the suggestion! Naninovel doesn't currently have a concept of story branches or endings; they're something developer of the game may or may not use in the project, hence I'm not sure it makes sense to introduce them as core concepts to the engine. Maybe it will be more appropriate to make a standalone system (example implementation), that could be added to the project when needed.

Okay I see, that might be better solution. Btw it might already been suggested but a in-game inventory system ([exampel pic](https://github.com/Elringus/NaninovelWeb/issues/40)) would be nice. Another thing I have seen is Character Profile Gallery ([exampel image)](https://i.imgur.com/fFarTJ3.png) like CG gallery but for characters. 

Maybe those also suits better for standalones, anyway that's some few features I also noticed in other novel games.

**Comment by Elringus** [comment]
This is now possible with the unlockables system coming in v1.5. Check out the guide for more info and `ICGGallery` prefab for example implementation of a similar system.
