### ISSUE TITLE
Waiting for input icon disappeared after the game loaded from a save

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#41]
>**Describe the bug**

I am not sure this is by design or really a bug. But I am still reporting it, feel free to close this issue if it is not considered as a bug.

Waiting for input icon disappeared after the game loaded from a save.

>**To Reproduce**
>1. Go to '...'
>2. Click on '....'
>3. Scroll down to '....'
>4. See error

1. Play the game
2. Save the game (Either quick save or normal save)
3. Load the saved game

>**Expected behavior**

Waiting for input icon should appear normally.

>**Screenshots**

**Before loaded from a save**
<img width="1440" alt="螢幕快照 2019-04-07 上午8 49 09" src="https://user-images.githubusercontent.com/5277788/55677059-d7b93280-5913-11e9-980e-be560ef792a7.png">

**Loading from a save**
<img width="1440" alt="螢幕快照 2019-04-07 上午8 49 20" src="https://user-images.githubusercontent.com/5277788/55677069-ef90b680-5913-11e9-99f3-b2e006237c89.png">

**After loaded from a save, waiting for input icon disappeared**
<img width="1440" alt="螢幕快照 2019-04-07 上午8 49 25" src="https://user-images.githubusercontent.com/5277788/55677076-1222cf80-5914-11e9-9c59-09e4cb24e1bc.png">

>**Naninovel version**
Version of the engine as displayed in `Naninovel -> About` window, e.g.: 1.0.12-beta

v1.3.2-beta build 2019-03-08

>**Unity version**
Specify Unity version you are using, e.g.: 2018.3.5f2.

2018.3.11f1

>**OS (when editor-related)**
Which operating system you're running the editor under, e.g.: Windows 10

macOS 10.14.4

>**Platform**
Which target platform you're using, e.g.: WebGL

PC, Mac & Linux Standalone (Mac OS X)

**Comment by Elringus** [comment]
Definitely a bug, thanks for reporting!

**Comment by Elringus** [comment]
Fixed in `v1.4.0-beta`.
