### ISSUE TITLE
Appearances path won't change after changing the character name

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#42]
>**Describe the bug**

Appearances path won't change after changing the character name (ID) in project settings. It will just prepend the new name to appearances path.

>**To Reproduce**
>1. Go to '...'
>2. Click on '....'
>3. Scroll down to '....'
>4. See error

1. Open project settings in `Naninovel -> Configuration` context menu.
2. Go to characters tab
3. Change a character's name.
4. Go into the character's detail settings
5. Back to characters
6. Change the character's name again

>**Expected behavior**

Appearances path should change to the new character name. Not prepend the new name to appearances path.

>**Screenshots**

**Character name (ID) with "Angel"**
<img width="604" alt="螢幕快照 2019-04-07 上午9 15 22" src="https://user-images.githubusercontent.com/5277788/55677296-ad697400-5917-11e9-8d2a-4c5ce24488c5.png">

**Appearances path before changing the character name**
<img width="589" alt="螢幕快照 2019-04-07 上午9 15 16" src="https://user-images.githubusercontent.com/5277788/55677304-cb36d900-5917-11e9-9369-b81d46d1f1ef.png">

**Changing character name (ID) to "AngelNew"**
<img width="604" alt="螢幕快照 2019-04-07 上午9 15 38" src="https://user-images.githubusercontent.com/5277788/55677315-df7ad600-5917-11e9-9e8a-41473e843504.png">

**See error**
<img width="593" alt="螢幕快照 2019-04-07 上午9 15 45" src="https://user-images.githubusercontent.com/5277788/55677320-033e1c00-5918-11e9-992f-6d74ac8be997.png">

>**Naninovel version**
Version of the engine as displayed in `Naninovel -> About` window, e.g.: 1.0.12-beta

v1.3.2-beta build 2019-03-08

>**Unity version**
Specify Unity version you are using, e.g.: 2018.3.5f2.

2018.3.11f1

>**OS (when editor-related)**
Which operating system you're running the editor under, e.g.: Windows 10

macOS 10.14.4

>**Platform**
Which target platform you're using, e.g.: WebGL

PC, Mac & Linux Standalone (Mac OS X)

**Comment by Elringus** [comment]
Well, yeah, that's kinda complicated. I'm currently re-writing the config system and it will handle this case when the appearance names are equal to the sprite names, but otherwise the names will still be lost when re-naming the actor. I will think if there is a way to handle that.

**Comment by Elringus** [comment]
Fixed in `v1.4.0-beta`.

https://i.gyazo.com/6d6f1b09b448bd6854df395319e6592e.mp4
