### ISSUE TITLE
Add script action to clear printer backlog

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#43]
>**Describe your idea**
A clear and concise description what should we change or add.

Sometimes we need to clear printer backlog (eg, Load a new game) to prevent confusion of the dialogue. Adding something like `@clearBacklog` would be useful.

>**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

- Load a new game
- Go to a new chapter, story or scene.
- Back to title and start a new game

>**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

Some other VN engines does allow to clear printer backlog. And considered it as an essential feature.

**Comment by Elringus** [comment]
Good idea! I guess we should just automatically clear it when loading a game or going back to the title (things like that can't be controlled via novel scripts) and add the action, so that users can also clear it when they wish.

**Comment by Elringus** [comment]
Fixed in `v1.4.0-beta`.

https://naninovel.com/api/#clearbacklog
