### ISSUE TITLE
Improving the settings menu

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#45]
In this thread I'd like to accumulate any ideas and suggestions regarding the in-game settings menu: what could we add or change to make them more helpful and user-friendly? Any comments and references (eg, setting menus from other VN engines or games) are welcome in this topic or via the discord server and private messages.

- [x] Re-design the built-in UI for easier customization; make all the controls (including sub-menu categories/tabs) removable / replaceable.
- [x] Add an option to change [graphics quality levels](https://docs.unity3d.com/Manual/class-QualitySettings.html) to optimize performance.
- [x] In the text settings menu (message speed, font, etc) add a preview printer that will print a stub text in a loop. This will allow to immediately see the effect of the changes, without returning to the game (merged from #23).
- [x] Allow changing font (size, type?) in the text settings menu.
- [ ] ~~Shortcut (key binding) settings.~~ Use axis in the input binging config instead; [the axis can then be configured in builds via Unity's launcher](https://docs.unity3d.com/Manual/ConventionalGameInput.html)

**Comment by AriAriAri3** [comment]
Hi, if I might add a suggestion here - it would be great to have some accessibility options added into the settings eg. make the font larger, or make the text box contrast more visible, or switch to a dyslexia-friendly font, or disable camera effects for people who get headaches easily etc.

Here's an example of some accessibility settings that were designed for renpy:
https://minute.itch.io/renpy-accessibility

Naninovel looks amazing, thank you for creating it :)

**Comment by AriAriAri3** [comment]
One additional thought- if you haven't already seen it, here's the full list of settings renpy allows the user to control:
https://www.renpy.org/wiki/renpy/Help
(Speed at which text will auto-play, the choice to turn transitions on and off etc.)

This page also contains the full list of keyboard shortcuts that are default to renpy. Would you, perhaps, consider incoprorating these keyboard shortcuts into naninovel? Most visual novel readers will be used to these shortcuts, and so it would be really handy for writers to have all these keyboard shutcuts enabled.

Thank you very much!

**Comment by Elringus** [comment]
I was going to add a font config option to the settings, just forgot to mention it here. Other stuff is kinda project-based (depends on the assets used in the game), so it'd more appropriate to implement it on per-project basis.

Regarding the shortcuts, they're already available in the input configuration.

**Comment by Elringus** [comment]
Ah, pardon me, did you mean the ability for player to set shortcuts in the game settings? That's actually a fair idea, I've somehow missed that :) Will add that option as well, thanks for the suggestion!

**Comment by LinkuArt** [comment]
To be able to use arrow keys to select menu & dialogue choices and would be helpful.

**Comment by Elringus** [comment]
> 
> 
> To be able to use arrow keys to select menu & dialogue choices and would be helpful.

It's actually already possible, you just have to set a focus on the UI to enable the navigation. I'm not enabling this by default, as it could interfere with the usual mouse control.

**Comment by AriAriAri3** [comment]
Just want to say thank you for being so responsive to suggestions! I've purchased naninovel and am looking forward to the stable release :)

(Please delete this if not appropriate here - just wanted to say thank you somewhere!)

**Comment by Elringus** [comment]
Implemented in `v1.9`.

**Comment by edisonlee55** [comment]
The shortcut (key binding) settings should be implemented because Unity's Resolution & Input Dialog (Unity's launcher) has been deprecated.

Reference: 
[The Display Resolution Dialogue has been deprecated and will be removed in a future version - Unity Forum](https://forum.unity.com/threads/the-display-resolution-dialogue-has-been-deprecated-and-will-be-removed-in-a-future-version.670798/#post-5312766)

**Comment by Elringus** [comment]
As you've correctly noticed, in v1.9 we support the new input system, which you can use to implement the key bindings at runtime: https://github.com/Elringus/NaninovelWeb/blob/v1.9/docs/guide/input-processing.md#input-system There are no plans to make any kind of built-in UI for runtime key bindings, though; in case it'll be a popular request, we could add an example on how to do that after the stable release.
