### ISSUE TITLE
Add support for visual scripting tools

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#48]
Expose core Naninovel APIs to the popular visual scripting extensions, like [Playmaker](https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-368) and [Bolt](https://assetstore.unity.com/packages/tools/visual-scripting/bolt-87491).

https://hutonggames.fogbugz.com/default.asp?W166
https://hutonggames.fogbugz.com/default.asp?W714

**Comment by TowerCrow** [comment]
+ for Bolt integration. It might not even need a bridge as long as the functionality is exposed via API but I'm not really an experienced programmer. 

Here's how Dialogue System developer did it via Bolt's built-in Unit Options Wizard.  https://www.pixelcrushers.com/dialogue_system/manual2x/html/bolt.html That's the beauty of Bolt, it supports most assets out of the box as long more advanced stuff doesn't come into play such as event callbacks which would need C#. 

Personally, I'd like for Bolt to be able to get and set Naninovel's variables (or maybe have them synced). And at least to be able to trigger a Bolt custom event from Naninovel.

Some common use cases I'd like to see covered:
1. Branching dialogue options displayed based on Bolt variables (or based on Naninovel variables that were set by Bolt).
2. Check inventory for a matching item or add an item to inventory in a form of triggering a custom Bolt event with an argument. (similar to how the Dialogue system does it via it's LUA scripting environment in the link above)
3. Trigger a Bolt custom event upon start, end or mid-conversation.

**Comment by Elringus** [comment]
> 
> 
> I'd really like to see Bolt integration. It might not even need a bridge as long as the functionality is exposed via API but I'm not really an experienced programmer.
> 
> Here's how Dialogue System developer did it via Bolt's built-in Unit Options Wizard. https://www.pixelcrushers.com/dialogue_system/manual2x/html/bolt.html That's the beauty of Bolt, it supports most assets out of the box as long more advanced stuff doesn't come into play such as event callbacks which would need C#.
> 
> Personally, I'd like for Bolt to be able to get and set Naninovel's variables (or maybe have them synced). And at least to be able to trigger a Bolt custom event from Naninovel.
> 
> Some common use cases I'd like to see covered:
> 
>     1. Start a conversation with Bolt in games that are not pure VNs and have other modes of play.
> 
>     2. Branching dialogue options displayed based on Bolt variables (or based on Naninovel variables that were set by Bolt).
> 
>     3. Check inventory for a matching item or add an item to inventory in a form of triggering a custom Bolt event with an argument. (similar to how the Dialogue system does it via it's LUA scripting environment in the link above)
> 
>     4. Trigger a Bolt custom event upon start, end or mid-conversation. (I guess this is more or less the same as point 3)

Thanks for the suggestions! I've actually tried contacting Bolt stuff asking a voucher for the purpose of making this integration possible (and adding some docs/examples), but they didn't respond. One of our users also tried the forums, but to no avail as well. I think they still could react in case more users will ask them to.

**Comment by TowerCrow** [comment]
I'll see what I can do. Devs might be off for the Holidays but when they get back I'll get an answer to you about that voucher. 

Meanwhile, if you have time, you could apply for a free sponsored license via this link: https://ludiq.io/bolt/free

**Comment by Elringus** [comment]
Yeah, I've actually used that form in my initial attempt to contact them.

**Comment by TowerCrow** [comment]
I got in contact with their community manager and they say they just sent out the key to you. Hope you got it now.

**Comment by Elringus** [comment]
Yep, got it, thanks! Will try to finish the integration and docs/examples by the next release.

**Comment by Elringus** [comment]
An update regarding Bolt support: due to Bolt v1 not supporting generics for non-AOT platforms (Naninovel API uses them a lot) and Bolt v2 not working with Unity 2019, the integration is postponed until the issues are resolved by the Bolt team.

**Comment by Elringus** [comment]
Bolt support added in `v1.6.0-beta`. 

Setup docs: https://github.com/Elringus/NaninovelWeb/blob/v1.6/docs/guide/visual-scripting.md
Usage example: https://www.youtube.com/watch?v=w7PAhE7HO9c
