### ISSUE TITLE
Printer backlog doesn't have character name

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#51]
>**Describe the bug**

Printer backlog doesn't have the character name. ʕ ಡ ﹏ ಡ ʔ

>**To Reproduce**
>1. Go to '...'
>2. Click on '....'
>3. Scroll down to '....'
>4. See error

1. Play the game
2. Open printer backlog
3. See error

>**Expected behavior**

Printer backlog should have the character name.

>**Screenshots**

**Character name (ID) with "Angel"**
<img width="1440" alt="螢幕快照 2019-04-23 下午9 21 50" src="https://user-images.githubusercontent.com/5277788/56584614-ae382080-660e-11e9-8cb5-bd0edb8b05eb.png">

**See error**
<img width="1440" alt="螢幕快照 2019-04-23 下午9 21 55" src="https://user-images.githubusercontent.com/5277788/56584636-b8f2b580-660e-11e9-829b-22cbbba742d2.png">

>**Naninovel version**
Version of the engine as displayed in `Naninovel -> About` window, e.g.: 1.0.12-beta

v1.4.1-beta build 2019-04-18

>**Unity version**
Specify Unity version you are using, e.g.: 2018.3.5f2.

2019.1.0f2

>**OS (when editor-related)**
Which operating system you're running the editor under, e.g.: Windows 10

macOS 10.14.4

>**Platform**
Which target platform you're using, e.g.: WebGL

PC, Mac & Linux Standalone (Mac OS X)

**Comment by Elringus** [comment]
Ugh, guess I've broken something in one of the last updates. Thanks for letting me know, will fix that asap.

**Comment by Elringus** [comment]
Fixed in `v1.4.2-beta`.
