### ISSUE TITLE
Add more text styling option for novel scripts

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#55]
>**Describe your idea**
A clear and concise description what should we change or add.

Add more text styling option for novel scripts.
(eg, text position [left, center, right, top, bottom, custom position, margin and padding], underline, strikethrough, font border, ruby text, kerning, text opacity (alpha), image-based fonts, change different font, etc.)

>**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

- Moving text around the screen
- Add furigana using ruby text
- Design and arrange the printer text by using novel scripts

>**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

From Ren'Py Documentation:
[Text — Ren'Py Documentation](https://www.renpy.org/doc/html/text.html)
[Style Properties — Ren'Py Documentation](https://www.renpy.org/doc/html/style_properties.html)

**Comment by Elringus** [comment]
The in-text formatting (which can be applied via novel scripts) of the built-in printers is unfortunately limited by what Unity allows: https://docs.unity3d.com/Manual/StyledText.html We'll have to wait until TMPro becomes an integral part of Unity to discard the current system and support additional features out of the box.

That said, [TMPro extension](https://naninovel.com/guide/text-printers.html#textmesh-pro) could actually utilize all the [rich text stuff](http://digitalnativestudios.com/textmeshpro/docs/rich-text/) right now, I'll see if it's possible to extend the `@style` action to support the additional options.

**Comment by TowerCrow** [comment]
Are there any plans for them to actually integrate TMPro fully? As far as I know, there are no plans for that in the 2019 cycle.

**Comment by Elringus** [comment]
Not sure. I know they're planning to replace the uGUI with UIElements eventually, but idea which text rendering solution they'll use with it.

**Comment by Elringus** [comment]
Implemented in `v1.7.0-beta`. 

https://github.com/Elringus/NaninovelWeb/blob/ad3bf2083992351e943721469e2b8b19cc89fe6a/docs/guide/text-printers.md#text-styles

https://youtu.be/aWdq7YxIxkE
