### ISSUE TITLE
IDE extension for naninovel scripts

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#56]
>**Describe your idea**
A clear and concise description what should we change or add.

I knew that Naninovel is working on the extension for Atom, but add extension support for more variety of editor and IDE (eg, Visual Studio, Visual Studio Code, Sublime Text, etc.) would be awesome.

>**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

- Syntax highlighting
- Check for script errors
- Script auto-completion

>**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

Scripts are varied between different VN engines, some of VN engines do provide IDE extension for their scripts.

**Comment by Elringus** [comment]
While we would like to add support for as much editors as possible, the amount of work required to support even one editor is overwhelming for our current capabilities. 

To make things easier, we've decided to use [LSP](https://microsoft.github.io/language-server-protocol/) and [tree-sitter](http://tree-sitter.github.io/tree-sitter/) to build core parser once and then re-use it for different IDEs. 

We already have a working prototype of the parser, but one issue is blocking the release: LSP currently doesn't support syntax highlighting, so it still should be done individually for each IDE. Atom happened to support tree-sitter natively, so we just plugged it for syntax highlighting and are going to release the extension in the foreseeable future. For all the other IDEs we have wait until LSP will support the highlighting. Here is a corresponding thread on the official LSP repo in case you wish to track that: https://github.com/microsoft/vscode-languageserver-node/pull/367

**Comment by Elringus** [comment]
Support for Atom editor is now available.

https://youtu.be/njKxsjtewzA

https://github.com/Elringus/NaninovelWeb/blob/4c2502cb37acf97f7007ae6ba2b17995b871b238/docs/guide/naninovel-scripts.md#ide-support

**Comment by ImanCol** [comment]
Can you support Visual Studio Code?

**Comment by Elringus** [comment]
> 
> 
> Can you support Visual Studio Code?

As mentioned previously, support for other IDEs depends on LS protocol supporting syntax highlighting. When that happens, we'll consider including support for IDEs that comply with it (VS code is one of them).
