### ISSUE TITLE
Add community-driven translation system for the website

### ISSUE THREAD

**Issue by edisonlee55** [Elringus/NaninovelWeb#57]
>**Describe your idea**
A clear and concise description what should we change or add.

Add different languages translations for documents and editor interface.

Maybe consider hire a professional translator or create a community translation program.

Translation for people who is not native English speaker would be nice.

>**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

- Multi-language document
- Multi-language editor interface

>**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

Document translation by the community can be seen everywhere. Adding different languages could increase the user base.

**Comment by Elringus** [comment]
I was actually planning to add a community-driven translation system for the website, but only after the stable release. While we're still in beta, the existing docs are frequently changed and removed, so I guess it's not very practical to work on the translations right now.

**Comment by Elringus** [comment]
Implemented with the last vuepress update.
