### ISSUE TITLE
Unity crash when label is duplicated

### ISSUE THREAD

**Issue by Alatriste79** [Elringus/NaninovelWeb#60]
**Describe the bug**
Editor crashes when goto has 2 labels with the same name in the script.

**To Reproduce**
1. Create a choice button that goes to a label.
2. Make that label duplicated. (so the goto doesn't know where to go)

choice handler:ButtonArea button:Props/Item pos:788,97 goto:.Label1
# Label1
 some code here

# Label1
 some other code here.

**Expected behavior**
Some warning from the editor, but not a crash.

**Screenshots**

**Naninovel version**
Windows 1.6 beta

**Unity version**
2019.1.0f2

**OS (when editor-related)**
Win 7

**Platform**
Windows

**Additional context**

**Comment by Elringus** [comment]
It's working fine for me (no crashes, the choice just leads to the first `Label1`). Please try reproducing that in a clean new project and if the issue persist, share the project with me, so I can dig into this further.
