### ISSUE TITLE
Hide character and text printer after conversation is over

### ISSUE THREAD

**Issue by Alatriste79** [Elringus/NaninovelWeb#67]
Right now the text printer and the character are visible when the conversation is over. It would be nice to hide them automatically, as usually at this point we want either the user to take control or to change the background.

**Comment by Elringus** [comment]
Not sure what you mean be the "conversation".

**Comment by Alatriste79** [comment]
Just a dialogue:

`@char Joe
@char Dave
Joe: Hello
Dave: Goodbye `

After the last line of dialogue, the printer and the character should be closed if not set otherwise. In my test, after finishing the dialogue, both characters remain in the screen and the last sentence is displayed in the printer.

**Comment by Elringus** [comment]
And how the system suppose to detect that the dialogue has finished?

**Comment by Alatriste79** [comment]
Fair point. What about adding the "@stop"?

**Comment by Elringus** [comment]
You mean making the `@hideChars` and `@hideText` actions be automatically executed when using `@stop`? Stop can be used in multiple ways, eg to stop script execution after showing choices, so it's not possible. I can't really see why it's an issue to manually invoke a hide action when you need it.

**Comment by Elringus** [comment]
Closing this for now; feel free to re-open in case you have more thoughts on the topic.
