### ISSUE TITLE
"Look around" parallax effect

### ISSUE THREAD

**Issue by LinkuArt** [Elringus/NaninovelWeb#69]
**Describe your idea**
A clear and concise description what should we change or add.

> A parallax effect that follows the players mouse movement. The player can "look around" a scene and background image.

**Describe possible use cases**
A concrete example or two on how the proposed change could be used.

> To see more of the background and give more depth.

**Share reference implementations**
If applicable, add screenshots or links to other resources that shows a similar feature implemented in other VN engines or games.

> Here is a game using parallax effect: [Exampel](https://img.itch.zone/aW1hZ2UvNDE1MDM1LzIwNzI5OTUuZ2lm/original/9UmVGU.gif), [Exampel ](https://img.itch.zone/aW1hZ2UvNDE1MDM1LzIwNjkyMDIuZ2lm/original/G6rL%2FZ.gif)

https://youtu.be/ny9TIG0X4vQ?t=360
https://youtu.be/0rp-E2ULA5c https://youtu.be/L0I6W5vPg_k
https://www.youtube.com/watch?v=ogRe_Ca_EAk
https://twitter.com/i/status/1153760866254381056

**Comment by Elringus** [comment]
Not sure such feature is appropriate for a VN engine; do any other VN engine provide something like that? 

That said, such effect should be possible with animated backgrounds. Check Unity tutorials for mouse input and parallax effects for more info.

**Comment by Elringus** [comment]
VNgen for GameMaker: https://youtu.be/ny9TIG0X4vQ?t=360

**Comment by Elringus** [comment]
Implemented in `v1.8.0-beta`. 

Orhto-perspective camera modes are switched with `ortho` bool parameter of the `@camera` command.

Look around mode is activated with `@look` command.

https://youtu.be/rC6C9mA7Szw
