### ISSUE TITLE
todo command [Enhancement]

### ISSUE THREAD

**Issue by niokasgami** [Elringus/NaninovelWeb#76]
**Describe your idea**
In simple while working on your game you might not have all the resources and features implemented so sometime you might want to add notes from there and there. as comment is nice you might wants to have the system to make you remember to not forget to implement the rain etc.

here introduce the '@todo' command which would fire up a Debug.log message at the said lines for make you remember.

**Describe possible use cases**

- A sticky notes for make you remember to not forget to finish those features or to actually fix a bug etc.
- Ease of use who avoid you to have to scroll your whole game for make sure that you didn't forget to fix those 'todo' task

**Share reference implementations**
Syntax : 

 [TODO("ImplementRain", status : ongoing)]
The bracket is for make difference between Generic literal text and the command
I could have use @ but you already use a lots of command and I prefer keeping this technical command out of the 'game' context.

How it would work : 
The todo will continue to fire up a message until their status is set to 'final' or is erased.
when they are in final they are muted and ignored like comment. 
It's also ignored on the final build.

On a possible note it could be also added as a futur command for the IDE support

as I said it'S not a super overly important command and mainly for help people to keep task in check.

**Comment by Elringus** [comment]
Stuff like this is usually tied to IDEs, not sure firing a debug log as a command would actually be practical. 

There are several extensions to manage todo tasks in Atom, check them out: https://atom.io/packages/search?q=todo

And in case you still want a command to print in the log, check out the guide on adding custom commands: https://naninovel.com/guide/custom-commands.html
