### ISSUE TITLE
Special effects

### ISSUE THREAD

**Issue by Elringus** [Elringus/NaninovelWeb#8]
Eventually, we would like to have the following built-in [special effects](https://naninovel.com/guide/special-effects.html) in the stable release:

- [x] Shake actors (printers, characters, backgrounds, etc)
- [x] Ping-pong movement (floating characters)
- [x] Camera glitch
- [x] Rain
- [x] Snow
- [x] Allow adding custom post-processing effects

Feel free to add your suggestions in this thread.

**Comment by wrighp** [comment]
It would be nice to have fx spawning and despawning actions for fx that may last for longer durations (Like for rain or fireworks that play until they are stopped).
The current solution I’m using is to spawn a prefab for something like rain and then spawn a prefab that destroys it.

**Comment by wrighp** [comment]
More specifically a stopFx action would be nice to destroy fx objects at the correct times.

**Comment by Elringus** [comment]
Rain effect added in `v1.3.0-beta`.
https://naninovel.com/guide/special-effects.html#rain

**Comment by Elringus** [comment]
Custom post-processing effects can be added in `v1.6.0-beta`.

https://github.com/Elringus/NaninovelWeb/blob/v1.6/docs/guide/special-effects.md#camera-effects

**Comment by Elringus** [comment]
Snow effect added in `v.1.6.0-beta`.
https://i.gyazo.com/25a052444c561e40c8318272f51edf47.mp4
