### ISSUE TITLE
Unable to show console in MacOS

### ISSUE THREAD

**Issue by giggioz** [Elringus/NaninovelWeb#9]
**Describe the bug**
I’m unable to make the console appear during the game with ~.
I have a macbook and to get ~ you need to press alt+5 and it does not work (it seems to interact with the Unity Hand Tool because of the alt button, i think).

**Naninovel version**
v1.1.0-beta build 2019-01-13

**Unity version**
2018.3.1f1

**OS (when editor-related)**
MacOS Mojave 10.14.2

**Comment by Elringus** [comment]
Thank you for reporting the issue! 

An option to rebind toggle console key will be added in the next update:

![](https://i.gyazo.com/e1ccf2a3c6859286be319006836b2660.png)

If you wish, contact me via support email or PM on Unity forum and I'll send you an updated package, which already has this feature.

**Comment by giggioz** [comment]
Great 👍 
I'm still playing with the framework, I have no need of having the updated package (yet 😄 )
