### ISSUE TITLE
Feature Request：Provide a Graphic Editor to edit NaniScript

### ISSUE THREAD

**Issue by keven2148** [Elringus/NaninovelWeb#96]
Hello, I'm glad to find this so great egine you provide in Unity asset store. But for my team,there are some troubles to make NaniScript. Our writer don't know how to code.It's too difficult for her to  make game by writing NaniScript.So we make a editor to help her edit the scene.Like this one
![图片1](https://user-images.githubusercontent.com/33781038/65408319-8ba57000-de17-11e9-85eb-0d54d28a273b.png)
Well, it look like the Frankenstein(because the guy who make UI left before it done), but truly useful.Even our artist can also edit effect of scenes, better than writer. Our editor can read or load NaniScript. Can read Image/live2d in the disk. Can add effect, even custom Effect. Can preview after make any instructions.
So, if you can provide a editor not just edit in Unity, it can help guys who don't know how to use unity to make a galgame, specially for a complex team.
There are some suggestions about make editor for engine.If you want to make it:
1.Need to add a command to roll back the game, not just "rewind", but a command can play from first line to designated line within one frame, make sure the background, char, any other resources correct. After adding that, my team can preview any element(a struct we assign in the editor) freely.
2.Editor can read file in hard disk.
I'm so sorry we can't provide code.The company don't allow us to do that.But i think it not so difficult for you to make a fantastic editor,not a Frankenstein.

**Comment by Elringus** [comment]
Hi, Thanks for the suggestions and sharing concept of the editor!

We've recently added a visual editor: https://naninovel.com/guide/naninovel-scripts.html#visual-editor What do you think of it, can it conceptually replace the editor you've mentioned (given we add some additional features)?

Regarding the rollback, we've also added a proper support for that, check out the latest release on the store.

**Comment by keven2148** [comment]
> Hi, Thanks for the suggestions and sharing concept of the editor!
> 
> We've recently added a visual editor: https://naninovel.com/guide/naninovel-scripts.html#visual-editor What do you think of it, can it conceptually replace the editor you've mentioned (given we add some additional features)?
> 
> Regarding the rollback, we've also added a proper support for that, check out the latest release on the store.

Wow, it looks good. Unfortunately we make the game and editor rely on 1.7. If we have chance to make another game that has a lot of Story dialogues, we will try to use the visual editor.I watch the video about visual editor and have a question.
Can we change the NaniScript in runtime and see the changes immediately by using rollback? As our write said, it hard to confirm params(like pos) in one time.So she will always run the scene and change the value.As the video show,it's a little inconvenient to run the script again.(Well, in our editor, our solution is using mouse or toggle bar to move sprite, recording the sprite's position and write it back to the script)
About the rollback, I'm so happy to see that you provide it in 1.8 version.If we can find this method easily,it really can help us to make some extensions :D

**Comment by Elringus** [comment]
It's currently possible to check the effect of a command at runtime by executing the command via debug console: https://naninovel.com/guide/development-console.html#executing-commands 

I'm also planning to allow editing currently played command in the visual editor, so it'll be possible to iterate without having to restart the game.

**Comment by Elringus** [comment]
The hot-reload feature, allowing to edit currently played commands via visual editor, has been implemented in `v1.9` (currently available as a pre-release for registered users).

**Comment by katrinshtorm** [comment]
https://github.com/naninovel/docs/issues/96#issue-496950270
Amazing! Your editor is truly stunning!
It's been almost 5 years now, is it possible to download this script for Unity?

The Graphic Editor for editing NaniScript that exists now is terrible!!
I say this as someone who configures avatars for VRChat and knows Unity quite well. Yet, the Graphic Editor for editing NaniScript is absolutely not user-friendly!
Yes, I can edit it manually = line by line, but that's not what should be associated with the term "Visual Graphic Editor for visual novels." 
Your script is a great example of the direction NaniScript should be heading (and I'm not sure if it will get there, but it would be great if it did!).
